// Code generated by ogen, DO NOT EDIT.
package server

type APIAgentNewPostRes interface {
	aPIAgentNewPostRes()
}

type APIAgentTaskExportPostRes interface {
	aPIAgentTaskExportPostRes()
}

type APIBookDetailsPostRes interface {
	aPIBookDetailsPostRes()
}

type APIBookListPostRes interface {
	aPIBookListPostRes()
}

type APIFileIDGetRes interface {
	aPIFileIDGetRes()
}

type APISystemHandlePostRes interface {
	aPISystemHandlePostRes()
}

type APISystemImportArchivePostRes interface {
	aPISystemImportArchivePostRes()
}

type APISystemInfoGetRes interface {
	aPISystemInfoGetRes()
}

type APIUserLoginPostRes interface {
	aPIUserLoginPostRes()
}
