// Code generated by ogen, DO NOT EDIT.
package client

type APICoreStatusGetRes interface {
	aPICoreStatusGetRes()
}

type APIExportArchivePostRes interface {
	aPIExportArchivePostRes()
}

type APIParsingBookCheckPostRes interface {
	aPIParsingBookCheckPostRes()
}

type APIParsingBookPostRes interface {
	aPIParsingBookPostRes()
}

type APIParsingPageCheckPostRes interface {
	aPIParsingPageCheckPostRes()
}

type APIParsingPagePostRes interface {
	aPIParsingPagePostRes()
}
