run:
  skip-files:
    - ".*_gen\\.go"

linters-settings:
  goimports:
    local-prefixes: github.com/gbh007/hgraber-next
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gbh007/hgraber-next)

linters:
  # disable-all: true
  enable:
    - gci
    - goimports
    - wsl
    - promlinter
