version: "2"

run:
  timeout: "5m"
  go: "1.25"

formatters:
  settings:
    gofumpt:
      extra-rules: true
    gci:
      no-inline-comments: false
      no-prefix-comments: false
      custom-order: true
      no-lex-order: false
      sections:
        - standard
        - default
        - localmodule
  enable:
    - gofumpt
    - goimports
    - gci

linters:
  default: none

  exclusions:
    warn-unused: true
    generated: strict
    paths:
      - .hidden
    rules:
      - linters:
          - err113
        text: do not define dynamic errors

  settings:
    copyloopvar:
      check-alias: true
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
      verbose: false
    gocritic:
      disable-all: true
      enable-all: false
      enabled-checks:
        - appendAssign
        - appendCombine
        - argOrder
        - assignOp
        - badCall
        - badCond
        - badLock
        - badRegexp
        - badSorting
        - badSyncOnceFunc
        - boolExprSimplify
        - builtinShadow
        - builtinShadowDecl
        - caseOrder
        - commentedOutCode
        - commentedOutImport
        - defaultCaseOrder
        - deferInLoop
        - deferUnlambda
        - deprecatedComment
        - dupArg
        - dupBranchBody
        - dupCase
        - dupImport
        - dupOption
        - dupSubExpr
        - dynamicFmtString
        - elseif
        - emptyDecl
        - emptyFallthrough
        - equalFold
        - evalOrder
        - exitAfterDefer
        - exposedSyncMutex
        - externalErrorReassign
        - filepathJoin
        - flagDeref
        - flagName
        - httpNoBody
        - ifElseChain
        - importShadow
        - indexAlloc
        - initClause
        - mapKey
        - methodExprCall
        - nestingReduce
        - newDeref
        - nilValReturn
        - octalLiteral
        - offBy1
        - preferDecodeRune
        - preferFilepathJoin
        - preferFprint
        - preferStringWriter
        - preferWriteByte
        - ptrToRefParam
        - rangeAppendAll
        - redundantSprint
        - regexpMust
        - regexpPattern
        - regexpSimplify
        - returnAfterHttpError
        - singleCaseSwitch
        - sliceClear
        - sloppyLen
        - sloppyReassign
        - sloppyTypeAssert
        - sortSlice
        - sqlQuery
        - stringConcatSimplify
        - stringXbytes
        - stringsCompare
        - switchTrue
        - syncMapLoadAndDelete
        - timeExprSimplify
        - todoCommentWithoutDetail
        - tooManyResultsChecker
        - truncateCmp
        - typeAssertChain
        - typeSwitchVar
        - typeUnparen
        - uncheckedInlineErr
        - underef
        - unlabelStmt
        - unlambda
        - unnecessaryBlock
        - unnecessaryDefer
        - unslice
        - valSwap
        - weakCond
        - whyNoLint
        - wrapperFunc
        - yodaStyleExpr
        - zeroByteRepeat
      settings:
        commentedOutCode:
          minLength: 3
        ifElseChain:
          minThreshold: 3
        nestingReduce:
          bodyWidth: 5
        tooManyResultsChecker:
          maxResults: 4
    govet:
      disable-all: true
      enable:
        - appends
        - asmdecl
        - assign
        - atomic
        - atomicalign
        - bools
        - buildtag
        - cgocall
        - composites
        - copylocks
        - deepequalerrors
        - defers
        - directive
        - errorsas
        - findcall
        - framepointer
        - hostport
        - httpmux
        - httpresponse
        - ifaceassert
        - loopclosure
        - lostcancel
        - nilfunc
        - nilness
        - printf
        - reflectvaluecompare
        - shift
        - sigchanyzer
        - slog
        - sortslice
        - stdmethods
        - stdversion
        - stringintconv
        - structtag
        - testinggoroutine
        - tests
        - timeformat
        - unmarshal
        - unreachable
        - unsafeptr
        - unusedresult
        - unusedwrite
        - waitgroup
    revive:
      enable-all-rules: false
      rules:
        - name: atomic
        - name: blank-imports
        - name: bool-literal-in-expr
        - name: comment-spacings
          arguments:
            - build
            - nolint
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
          arguments:
            - allow-types-before: "*testing.T"
        - name: context-keys-type
        - name: datarace
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: error-naming
        - name: error-return
          severity: warning
        - name: error-strings
        - name: errorf
        - name: filename-format
          arguments:
            - "^[a-z][_a-z0-9]*\\.go$"
        - name: forbidden-call-in-wg-go
        - name: get-return
        - name: identical-branches
        - name: identical-ifelseif-branches
        - name: identical-ifelseif-conditions
        - name: identical-switch-conditions
        - name: if-return
        - name: import-alias-naming
          arguments:
            - "^[a-z][a-z0-9]{0,}$"
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: inefficient-map-lookup
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: optimize-operands-order
        - name: range
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: redundant-import-alias
        - name: redundant-test-main-exit
        - name: string-format
          arguments:
            - - "fmt.Errorf[0]"
              - "/^((.+: )+%\\w)|(%\\w(: .+)+)$/"
              - "need use format"
        - name: string-of-int
        - name: superfluous-else
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
        - name: unnecessary-if
        - name: unnecessary-format
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: use-any
        - name: use-errors-new
        # FIXME: включить правило как появится в golangcilint
        # - name: use-slices-sort
        - name: use-waitgroup-go
        - name: useless-break
        - name: useless-fallthrough
        - name: var-declaration
        - name: waitgroup-by-value
    sloglint:
      kv-only: false
      no-mixed-args: true
      attr-only: true
      no-global: all
      context: scope
      static-msg: true
      msg-style: lowercased
      no-raw-keys: false
      key-naming-case: snake
      args-on-sep-lines: false
      forbidden-keys:
        - err
    testifylint:
      enable-all: true
    usetesting:
      os-create-temp: true
      os-mkdir-temp: true
      os-setenv: true
      os-temp-dir: true
      os-chdir: true
      context-background: true
      context-todo: true

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forcetypeassert
    - gocheckcompilerdirectives
    - gocritic
    - govet
    - iface
    - ineffassign
    - intrange
    - iotamixing
    - mirror
    - modernize
    - musttag
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl_v5
