application:
  debug:
    logs: true
  metric:
    scrape_period:
      main_info: 10s
      book_statistic: 1h0m0s
  service_name: hgraber-next-local-test
  trace_endpoint: ""
  pyroscope:
    endpoint: ""
    debug: false
    rate: 5
parsing:
  parse_book_timeout: 5m
  agent_timeout: 10m
workers:
  page:
    count: 1
    queue_size: 100
    interval: 3s
  book:
    count: 1
    queue_size: 100
    interval: 3s
  hasher:
    count: 1
    queue_size: 100
    interval: 3s
  exporter:
    count: 1
    queue_size: 100
    interval: 3s
  tasker:
    count: 1
    queue_size: 100
    interval: 10s
  file_validator:
    count: 1
    queue_size: 100
    interval: 3s
  file_transferer:
    count: 1
    queue_size: 100
    interval: 3s
storage:
  debug_squirrel: false
  debug_pgx: false
  connection: postgres://hgrabernextuser:hgrabernextpass@localhost:5432/hgrabernext?sslmode=disable
  max_connections: 10
file_storage:
  try_reconnect: true
api:
  addr: 127.0.0.1:8080
  external_addr: http://localhost:8080
  static_dir: internal/controllers/apiserver/internal/static
  token: local-next
  log_error_handler: false
  debug: false
agent_server:
  addr: 127.0.0.1:8085
  token: local-cache
  log_error_handler: false
  debug: false
