application:
  debug:
    logs: true
    db: false
    api_server: false
    api_agent: false
  metric:
    scrape_period:
      main_info: 10s
      book_statistic: 1h0m0s
  service_name: hgraber-next-local-test
parsing:
  parse_book_timeout: 5m
  agent_timeout: 10m
workers:
  page:
    count: 1
    queue_size: 10000
    interval: 3s
  book:
    count: 1
    queue_size: 1000
    interval: 3s
  hasher:
    count: 1
    queue_size: 1000
    interval: 3s
  exporter:
    count: 1
    queue_size: 100
    interval: 3s
  tasker:
    count: 1
    queue_size: 100
    interval: 10s
storage:
  connection: postgres://hgrabernextuser:hgrabernextpass@localhost:5432/hgrabernext?sslmode=disable
  file_path: ./.hidden/filedata
  max_connections: 10
  # fs_agent_id: 019067fc-8d4f-769d-8c4f-e755597f9525
api:
  addr: 127.0.0.1:8080
  external_addr: http://localhost:8080
  static_dir: internal/controllers/apiserver/internal/static
  token: local-next
agent_server:
  addr: 127.0.0.1:8085
  token: local-cache
