{
 "title": "Hgraber next",
 "tags": [ "hgnext" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "logs",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "metrics", "query": "prometheus" },
   {
    "name": "service_name",
    "query": "label_values(hgraber_next_version_info, service_name)"
   },
   { "name": "deltaInterval", "query": "1m,5m,10m,30m,1h,4h,8h,1d,7d" }
  ]
 },
 "panels": [
  { "title": "Simple info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Book count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (hgraber_next_server_book_total{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Page count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (hgraber_next_server_page_total{service_name=~\"$service_name\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "File size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",service_type=\"server\",type=\"fs\"})",
     "legendFormat": "На диске"
    },
    {
     "expr": "sum by (type) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",service_type=\"server\",type=\"page\"})",
     "legendFormat": "В страницах"
    }
   ]
  },
  {
   "title": "FS Compression",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1) - ((sum by (fs_id) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",service_type=\"server\",type=\"fs\"})) / (sum by (fs_id) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",service_type=\"server\",type=\"page\"})))",
     "legendFormat": "{{fs_id}}"
    }
   ]
  },
  {
   "title": "Book delta count at $deltaInterval",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (delta(hgraber_next_server_book_total{service_name=~\"$service_name\",service_type=\"server\"}[$deltaInterval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Page delta count at $deltaInterval",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (delta(hgraber_next_server_page_total{service_name=~\"$service_name\"}[$deltaInterval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "File delta count at $deltaInterval",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (type) (delta(hgraber_next_fs_file_total{service_name=~\"$service_name\",service_type=\"server\"}[$deltaInterval]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "File delta size at $deltaInterval",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (delta(hgraber_next_fs_file_bytes{service_name=~\"$service_name\",type=\"fs\",service_type=\"server\"}[$deltaInterval]))",
     "legendFormat": "На диске"
    },
    {
     "expr": "sum by (type) (delta(hgraber_next_fs_file_bytes{service_name=~\"$service_name\",type=\"page\",service_type=\"server\"}[$deltaInterval]))",
     "legendFormat": "В страницах"
    }
   ]
  },
  {
   "title": "Worker errors at $deltaInterval",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (success) (increase(hgraber_next_server_worker_execution_task_seconds_count{service_name=~\"$service_name\"}[$deltaInterval]))",
     "legendFormat": "{{success}}"
    }
   ]
  },
  {
   "title": "FS size",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (fs_id) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",service_type=\"server\",type=\"fs\"})",
     "legendFormat": "{{fs_id}}"
    }
   ]
  },
  {
   "title": "Worker handle at $deltaInterval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (worker_name, success) (increase(hgraber_next_server_worker_execution_task_seconds_count{service_name=~\"$service_name\"}[$deltaInterval]))",
     "legendFormat": "{{worker_name}}/{{success}}"
    }
   ]
  },
  {
   "title": "Parser handle at $deltaInterval",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (action, parser_name) (increase(hgraber_next_agent_parser_action_seconds_count{service_name=~\"$service_name\"}[$deltaInterval]))",
     "legendFormat": "{{parser_name}} -> {{action}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "service_name : ($service_name)" }
   ]
  },
  {
   "title": "Books and pages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Book delta count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (delta(hgraber_next_server_book_total{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Page delta count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (delta(hgraber_next_server_page_total{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "File delta count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type, fs_id) (delta(hgraber_next_fs_file_total{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{type}} -> {{fs_id}}"
      }
     ]
    },
    {
     "title": "File delta size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (type, fs_id) (delta(hgraber_next_fs_file_bytes{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{type}} -> {{fs_id}}"
      }
     ]
    },
    {
     "title": "Book count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (hgraber_next_server_book_total{service_name=~\"$service_name\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Page count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type) (hgraber_next_server_page_total{service_name=~\"$service_name\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "File count",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (type, fs_id) (hgraber_next_fs_file_total{service_name=~\"$service_name\"})",
       "legendFormat": "{{type}} -> {{fs_id}}"
      }
     ]
    },
    {
     "title": "File size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (type, fs_id) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\"})",
       "legendFormat": "{{type}} -> {{fs_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "collapsed": true,
   "panels": [
    {
     "title": "Book sizes",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 70 },
     "targets": [
      {
       "expr": "sum by (le) (hgraber_next_statistic_book_size_bucket{service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Page sizes",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 70 },
     "targets": [
      {
       "expr": "sum by (le) (hgraber_next_statistic_page_size_bucket{service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Page in book",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 70 },
     "targets": [
      {
       "expr": "sum by (le) (hgraber_next_statistic_page_in_book_bucket{service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Page sizes by authors",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "sum by (le) (hgraber_next_statistic_pages_size_by_author_bucket{service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Book by authors",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 79 },
     "targets": [
      {
       "expr": "sum by (le) (hgraber_next_statistic_books_by_author_bucket{service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Page by authors",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 79 },
     "targets": [
      {
       "expr": "sum by (le) (hgraber_next_statistic_pages_by_author_bucket{service_name=~\"$service_name\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Workers and agents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "Agent parsing avg latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (action, parser_name) (rate(hgraber_next_agent_parser_action_seconds_sum{service_name=~\"$service_name\"}[$__rate_interval]))) / (sum by (action, parser_name) (rate(hgraber_next_agent_parser_action_seconds_count{service_name=~\"$service_name\"}[$__rate_interval])))",
       "legendFormat": "{{parser_name}} -> {{action}}"
      }
     ]
    },
    {
     "title": "Agent parsing RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 89 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (action, parser_name) (rate(hgraber_next_agent_parser_action_seconds_count{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{parser_name}} -> {{action}}"
      }
     ]
    },
    {
     "title": "Worker avg latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (worker_name) (rate(hgraber_next_server_worker_execution_task_seconds_sum{service_name=~\"$service_name\"}[$__rate_interval]))) / (sum by (worker_name) (rate(hgraber_next_server_worker_execution_task_seconds_count{service_name=~\"$service_name\"}[$__rate_interval])))",
       "legendFormat": "{{worker_name}}"
      }
     ]
    },
    {
     "title": "Worker RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (worker_name) (rate(hgraber_next_server_worker_execution_task_seconds_count{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{worker_name}}"
      }
     ]
    },
    {
     "title": "Worker stat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (worker_name, counter) (hgraber_next_server_worker_total{service_name=~\"$service_name\"})",
       "legendFormat": "{{worker_name}} -> {{counter}}"
      }
     ]
    },
    {
     "title": "Web cache RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (action) (rate(hgraber_next_agent_web_cache_total{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "FS Compression",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1) - ((sum by (fs_id) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",type=\"fs\",service_type=\"server\"})) / (sum by (fs_id) (hgraber_next_fs_file_bytes{service_name=~\"$service_name\",type=\"page\",service_type=\"server\"})))",
       "legendFormat": "{{fs_id}}"
      }
     ]
    },
    {
     "title": "Worker stat",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (scrape_name) (hgraber_next_server_info_scrape_duration_seconds{service_name=~\"$service_name\"})",
       "legendFormat": "{{scrape_name}}"
      }
     ]
    },
    {
     "title": "FS latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (service_type, action, fs_id) (rate(hgraber_next_fs_action_seconds_sum{service_name=~\"$service_name\"}[$__rate_interval]))) / (sum by (service_type, action, fs_id) (rate(hgraber_next_fs_action_seconds_count{service_name=~\"$service_name\"}[$__rate_interval])))",
       "legendFormat": "{{service_type}}/{{action}} -> {{fs_id}}"
      }
     ]
    },
    {
     "title": "FS RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (action, fs_id) (rate(hgraber_next_fs_action_seconds_count{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{service_type}}/{{action}} -> {{fs_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, service_name, server_addr, operation, status) (rate(hgraber_next_http_server_handle_duration_bucket{service_name=~\"$service_name\"}[$__rate_interval])))",
       "legendFormat": "{{service_name}} {{server_addr}}/{{operation}} -> {{status}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 136 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (service_name, server_addr, operation, status) (rate(hgraber_next_http_server_handle_duration_count{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{service_name}} {{server_addr}}/{{operation}} -> {{status}}"
      }
     ]
    },
    {
     "title": "Active request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (service_name, server_addr, operation) (hgraber_next_http_server_active_handlers_total{service_name=~\"$service_name\"})",
       "legendFormat": "{{service_name}} {{server_addr}}/{{operation}}"
      }
     ]
    },
    {
     "title": "Slow request",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 145 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (service_name, server_addr, operation, status) (hgraber_next_http_server_handle_duration_sum{service_name=~\"$service_name\"})) / (sum by (service_name, server_addr, operation, status) (hgraber_next_http_server_handle_duration_count{service_name=~\"$service_name\"}))",
       "legendFormat": "{{service_name}} {{server_addr}}/{{operation}} -> {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency Q95",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by (le, stmt, db) (rate(hgraber_next_database_request_duration_bucket{service_name=~\"$service_name\"}[$__rate_interval])))",
       "legendFormat": "{{db}} -> {{stmt}}"
      }
     ]
    },
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (stmt, db) (rate(hgraber_next_database_request_duration_count{service_name=~\"$service_name\"}[$__rate_interval]))",
       "legendFormat": "{{db}} -> {{stmt}}"
      }
     ]
    },
    {
     "title": "Active request",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db) (hgraber_next_database_active_request{service_name=~\"$service_name\"})",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "Open connection",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (db) (hgraber_next_database_open_connection{service_name=~\"$service_name\"})",
       "legendFormat": "{{db}}"
      }
     ]
    },
    {
     "title": "Slow request",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(sum by (stmt, db) (hgraber_next_database_request_duration_sum{service_name=~\"$service_name\"})) / (sum by (stmt, db) (hgraber_next_database_request_duration_count{service_name=~\"$service_name\"}))",
       "legendFormat": "{{db}} -> {{stmt}}"
      }
     ]
    }
   ]
  }
 ]
}