// Code generated by ogen, DO NOT EDIT.

package serverapi

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// APIBookArchiveIDGetParams is parameters of GET /api/book/archive/{id} operation.
type APIBookArchiveIDGetParams struct {
	// ID книги для получения.
	ID uuid.UUID
}

func unpackAPIBookArchiveIDGetParams(packed middleware.Parameters) (params APIBookArchiveIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeAPIBookArchiveIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIBookArchiveIDGetParams, _ error) {
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// APIFileIDGetParams is parameters of GET /api/file/{id} operation.
type APIFileIDGetParams struct {
	// ID файла для получения.
	ID string
	// ID файловой системы, для ускорения получения файла.
	Fsid OptUUID
}

func unpackAPIFileIDGetParams(packed middleware.Parameters) (params APIFileIDGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "id",
			In:   "path",
		}
		params.ID = packed[key].(string)
	}
	{
		key := middleware.ParameterKey{
			Name: "fsid",
			In:   "query",
		}
		if v, ok := packed[key]; ok {
			params.Fsid = v.(OptUUID)
		}
	}
	return params
}

func decodeAPIFileIDGetParams(args [1]string, argsEscaped bool, r *http.Request) (params APIFileIDGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode path: id.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "id",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.ID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "id",
			In:   "path",
			Err:  err,
		}
	}
	// Decode query: fsid.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "fsid",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotFsidVal uuid.UUID
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToUUID(val)
					if err != nil {
						return err
					}

					paramsDotFsidVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.Fsid.SetTo(paramsDotFsidVal)
				return nil
			}); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "fsid",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// APIHproxyFileGetParams is parameters of GET /api/hproxy/file operation.
type APIHproxyFileGetParams struct {
	// Ссылка на книгу во внешней системе.
	BookURL url.URL
	// Ссылка на изображение во внешней системе.
	ImageURL url.URL
}

func unpackAPIHproxyFileGetParams(packed middleware.Parameters) (params APIHproxyFileGetParams) {
	{
		key := middleware.ParameterKey{
			Name: "book_url",
			In:   "query",
		}
		params.BookURL = packed[key].(url.URL)
	}
	{
		key := middleware.ParameterKey{
			Name: "image_url",
			In:   "query",
		}
		params.ImageURL = packed[key].(url.URL)
	}
	return params
}

func decodeAPIHproxyFileGetParams(args [0]string, argsEscaped bool, r *http.Request) (params APIHproxyFileGetParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: book_url.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "book_url",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToURL(val)
				if err != nil {
					return err
				}

				params.BookURL = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "book_url",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: image_url.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "image_url",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToURL(val)
				if err != nil {
					return err
				}

				params.ImageURL = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "image_url",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
