// Code generated by ogen, DO NOT EDIT.
package serverapi

type APIAgentDeletePostRes interface {
	aPIAgentDeletePostRes()
}

type APIAgentGetPostRes interface {
	aPIAgentGetPostRes()
}

type APIAgentListPostRes interface {
	aPIAgentListPostRes()
}

type APIAgentNewPostRes interface {
	aPIAgentNewPostRes()
}

type APIAgentTaskExportPostRes interface {
	aPIAgentTaskExportPostRes()
}

type APIAgentUpdatePostRes interface {
	aPIAgentUpdatePostRes()
}

type APIAttributeColorCreatePostRes interface {
	aPIAttributeColorCreatePostRes()
}

type APIAttributeColorDeletePostRes interface {
	aPIAttributeColorDeletePostRes()
}

type APIAttributeColorGetPostRes interface {
	aPIAttributeColorGetPostRes()
}

type APIAttributeColorListGetRes interface {
	aPIAttributeColorListGetRes()
}

type APIAttributeColorUpdatePostRes interface {
	aPIAttributeColorUpdatePostRes()
}

type APIAttributeCountGetRes interface {
	aPIAttributeCountGetRes()
}

type APIAttributeOriginCountGetRes interface {
	aPIAttributeOriginCountGetRes()
}

type APIAttributeRemapCreatePostRes interface {
	aPIAttributeRemapCreatePostRes()
}

type APIAttributeRemapDeletePostRes interface {
	aPIAttributeRemapDeletePostRes()
}

type APIAttributeRemapGetPostRes interface {
	aPIAttributeRemapGetPostRes()
}

type APIAttributeRemapListGetRes interface {
	aPIAttributeRemapListGetRes()
}

type APIAttributeRemapUpdatePostRes interface {
	aPIAttributeRemapUpdatePostRes()
}

type APIBookArchiveIDGetRes interface {
	aPIBookArchiveIDGetRes()
}

type APIBookDeletePostRes interface {
	aPIBookDeletePostRes()
}

type APIBookDetailsPostRes interface {
	aPIBookDetailsPostRes()
}

type APIBookListPostRes interface {
	aPIBookListPostRes()
}

type APIBookPageBodyPostRes interface {
	aPIBookPageBodyPostRes()
}

type APIBookPageDeletePostRes interface {
	aPIBookPageDeletePostRes()
}

type APIBookRawPostRes interface {
	aPIBookRawPostRes()
}

type APIBookRebuildPostRes interface {
	aPIBookRebuildPostRes()
}

type APIBookRestorePostRes interface {
	aPIBookRestorePostRes()
}

type APIBookStatusSetPostRes interface {
	aPIBookStatusSetPostRes()
}

type APIBookUpdatePostRes interface {
	aPIBookUpdatePostRes()
}

type APIDeduplicateArchivePostRes interface {
	aPIDeduplicateArchivePostRes()
}

type APIDeduplicateBookByPageBodyPostRes interface {
	aPIDeduplicateBookByPageBodyPostRes()
}

type APIDeduplicateBooksByPagePostRes interface {
	aPIDeduplicateBooksByPagePostRes()
}

type APIDeduplicateComparePostRes interface {
	aPIDeduplicateComparePostRes()
}

type APIDeduplicateDeadHashSetPostRes interface {
	aPIDeduplicateDeadHashSetPostRes()
}

type APIDeduplicateUniquePagesPostRes interface {
	aPIDeduplicateUniquePagesPostRes()
}

type APIFileIDGetRes interface {
	aPIFileIDGetRes()
}

type APIFsCreatePostRes interface {
	aPIFsCreatePostRes()
}

type APIFsDeletePostRes interface {
	aPIFsDeletePostRes()
}

type APIFsGetPostRes interface {
	aPIFsGetPostRes()
}

type APIFsListPostRes interface {
	aPIFsListPostRes()
}

type APIFsRemoveMismatchPostRes interface {
	aPIFsRemoveMismatchPostRes()
}

type APIFsTransferBookPostRes interface {
	aPIFsTransferBookPostRes()
}

type APIFsTransferPostRes interface {
	aPIFsTransferPostRes()
}

type APIFsUpdatePostRes interface {
	aPIFsUpdatePostRes()
}

type APIFsValidatePostRes interface {
	aPIFsValidatePostRes()
}

type APIHproxyBookPostRes interface {
	aPIHproxyBookPostRes()
}

type APIHproxyFileGetRes interface {
	aPIHproxyFileGetRes()
}

type APIHproxyListPostRes interface {
	aPIHproxyListPostRes()
}

type APILabelDeletePostRes interface {
	aPILabelDeletePostRes()
}

type APILabelGetPostRes interface {
	aPILabelGetPostRes()
}

type APILabelPresetCreatePostRes interface {
	aPILabelPresetCreatePostRes()
}

type APILabelPresetDeletePostRes interface {
	aPILabelPresetDeletePostRes()
}

type APILabelPresetGetPostRes interface {
	aPILabelPresetGetPostRes()
}

type APILabelPresetListGetRes interface {
	aPILabelPresetListGetRes()
}

type APILabelPresetUpdatePostRes interface {
	aPILabelPresetUpdatePostRes()
}

type APILabelSetPostRes interface {
	aPILabelSetPostRes()
}

type APIMassloadInfoAttributeCreatePostRes interface {
	aPIMassloadInfoAttributeCreatePostRes()
}

type APIMassloadInfoAttributeDeletePostRes interface {
	aPIMassloadInfoAttributeDeletePostRes()
}

type APIMassloadInfoCreatePostRes interface {
	aPIMassloadInfoCreatePostRes()
}

type APIMassloadInfoDeletePostRes interface {
	aPIMassloadInfoDeletePostRes()
}

type APIMassloadInfoExternalLinkCreatePostRes interface {
	aPIMassloadInfoExternalLinkCreatePostRes()
}

type APIMassloadInfoExternalLinkDeletePostRes interface {
	aPIMassloadInfoExternalLinkDeletePostRes()
}

type APIMassloadInfoGetPostRes interface {
	aPIMassloadInfoGetPostRes()
}

type APIMassloadInfoListGetRes interface {
	aPIMassloadInfoListGetRes()
}

type APIMassloadInfoUpdatePostRes interface {
	aPIMassloadInfoUpdatePostRes()
}

type APIParsingHandlePostRes interface {
	aPIParsingHandlePostRes()
}

type APIParsingMirrorCreatePostRes interface {
	aPIParsingMirrorCreatePostRes()
}

type APIParsingMirrorDeletePostRes interface {
	aPIParsingMirrorDeletePostRes()
}

type APIParsingMirrorGetPostRes interface {
	aPIParsingMirrorGetPostRes()
}

type APIParsingMirrorListGetRes interface {
	aPIParsingMirrorListGetRes()
}

type APIParsingMirrorUpdatePostRes interface {
	aPIParsingMirrorUpdatePostRes()
}

type APISystemImportArchivePostRes interface {
	aPISystemImportArchivePostRes()
}

type APISystemInfoSizeGetRes interface {
	aPISystemInfoSizeGetRes()
}

type APISystemInfoWorkersGetRes interface {
	aPISystemInfoWorkersGetRes()
}

type APISystemTaskCreatePostRes interface {
	aPISystemTaskCreatePostRes()
}

type APISystemTaskResultsGetRes interface {
	aPISystemTaskResultsGetRes()
}

type APISystemWorkerConfigPostRes interface {
	aPISystemWorkerConfigPostRes()
}

type APIUserLoginPostRes interface {
	aPIUserLoginPostRes()
}
