@startuml "goarchlint"
skinparam componentStyle rectangle
[/adapters/agent] --> [/adapters/agent/internal/adapter]
[/adapters/agent] --> [/domain/agentmodel]
[/adapters/agent] --> [/domain/core]
[/adapters/agent] --> [/domain/fsmodel]
[/adapters/agent] --> [/domain/hproxymodel]
[/adapters/agent/internal/adapter] --> [/domain/agentmodel]
[/adapters/agent/internal/adapter] --> [/domain/core]
[/adapters/agent/internal/adapter] --> [/domain/fsmodel]
[/adapters/agent/internal/adapter] --> [/domain/hproxymodel]
[/adapters/agent/internal/adapter] --> [/openapi/agentapi]
[/adapters/agent/internal/adapter] --> [/pkg]
[/adapters/agentfs] --> [/domain/fsmodel]
[/adapters/filestorage] --> [/adapters/agentfs]
[/adapters/filestorage] --> [/adapters/localfiles]
[/adapters/filestorage] --> [/domain/core]
[/adapters/filestorage] --> [/domain/fsmodel]
[/adapters/localfiles] --> [/domain/core]
[/adapters/localfiles] --> [/domain/fsmodel]
[/adapters/metric] --> [/adapters/metric/metricagent]
[/adapters/metric] --> [/adapters/metric/metriccore]
[/adapters/metric] --> [/adapters/metric/metricdatabase]
[/adapters/metric] --> [/adapters/metric/metricfs]
[/adapters/metric] --> [/adapters/metric/metrichttp]
[/adapters/metric] --> [/adapters/metric/metricserver]
[/adapters/metric] --> [/adapters/metric/metricstatistic]
[/adapters/metric] --> [/domain/core]
[/adapters/metric] --> [/domain/systemmodel]
[/adapters/metric/generator] --> [/adapters/metric/generator/bookandpages]
[/adapters/metric/generator] --> [/adapters/metric/generator/databasepanel]
[/adapters/metric/generator] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator] --> [/adapters/metric/generator/httpserverpanel]
[/adapters/metric/generator] --> [/adapters/metric/generator/logspannel]
[/adapters/metric/generator] --> [/adapters/metric/generator/otherpanel]
[/adapters/metric/generator] --> [/adapters/metric/generator/simpleinfo]
[/adapters/metric/generator] --> [/adapters/metric/generator/statistic]
[/adapters/metric/generator] --> [/adapters/metric/generator/workersandagents]
[/adapters/metric/generator] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/bookandpages] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/bookandpages] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/bookandpages] --> [/adapters/metric/metricfs]
[/adapters/metric/generator/bookandpages] --> [/adapters/metric/metricserver]
[/adapters/metric/generator/databasepanel] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/databasepanel] --> [/adapters/metric/metricdatabase]
[/adapters/metric/generator/generatorcore] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/generatorcore] --> [/pkg]
[/adapters/metric/generator/httpserverpanel] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/httpserverpanel] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/httpserverpanel] --> [/adapters/metric/metrichttp]
[/adapters/metric/generator/logspannel] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/otherpanel] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/otherpanel] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/otherpanel] --> [/adapters/metric/metricfs]
[/adapters/metric/generator/otherpanel] --> [/adapters/metric/metricserver]
[/adapters/metric/generator/simpleinfo] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/simpleinfo] --> [/adapters/metric/metricagent]
[/adapters/metric/generator/simpleinfo] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/simpleinfo] --> [/adapters/metric/metricfs]
[/adapters/metric/generator/simpleinfo] --> [/adapters/metric/metricserver]
[/adapters/metric/generator/statistic] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/statistic] --> [/adapters/metric/metricstatistic]
[/adapters/metric/generator/workersandagents] --> [/adapters/metric/generator/generatorcore]
[/adapters/metric/generator/workersandagents] --> [/adapters/metric/metricagent]
[/adapters/metric/generator/workersandagents] --> [/adapters/metric/metriccore]
[/adapters/metric/generator/workersandagents] --> [/adapters/metric/metricserver]
[/adapters/metric/metricagent] --> [/adapters/metric/metriccore]
[/adapters/metric/metriccore] --> [/version]
[/adapters/metric/metricdatabase] --> [/adapters/metric/metriccore]
[/adapters/metric/metricfs] --> [/adapters/metric/metriccore]
[/adapters/metric/metrichttp] --> [/adapters/metric/metriccore]
[/adapters/metric/metricserver] --> [/adapters/metric/metriccore]
[/adapters/metric/metricserver] --> [/domain/systemmodel]
[/adapters/metric/metricstatistic] --> [/adapters/metric/metriccore]
[/adapters/postgresql] --> [/adapters/postgresql/internal/agent]
[/adapters/postgresql] --> [/adapters/postgresql/internal/attribute]
[/adapters/postgresql] --> [/adapters/postgresql/internal/book]
[/adapters/postgresql] --> [/adapters/postgresql/internal/deadhash]
[/adapters/postgresql] --> [/adapters/postgresql/internal/file]
[/adapters/postgresql] --> [/adapters/postgresql/internal/label]
[/adapters/postgresql] --> [/adapters/postgresql/internal/massload]
[/adapters/postgresql] --> [/adapters/postgresql/internal/other]
[/adapters/postgresql] --> [/adapters/postgresql/internal/page]
[/adapters/postgresql] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql] --> [/adapters/postgresql/internal/urlmirror]
[/adapters/postgresql/internal/agent] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/agent] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/agent] --> [/domain/core]
[/adapters/postgresql/internal/attribute] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/attribute] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/attribute] --> [/domain/core]
[/adapters/postgresql/internal/book] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/book] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/book] --> [/domain/core]
[/adapters/postgresql/internal/deadhash] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/deadhash] --> [/domain/core]
[/adapters/postgresql/internal/deadhash] --> [/pkg]
[/adapters/postgresql/internal/file] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/file] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/file] --> [/domain/core]
[/adapters/postgresql/internal/file] --> [/domain/fsmodel]
[/adapters/postgresql/internal/label] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/label] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/label] --> [/domain/core]
[/adapters/postgresql/internal/massload] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/massload] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/massload] --> [/domain/massloadmodel]
[/adapters/postgresql/internal/model] --> [/domain/core]
[/adapters/postgresql/internal/model] --> [/domain/fsmodel]
[/adapters/postgresql/internal/model] --> [/domain/massloadmodel]
[/adapters/postgresql/internal/model] --> [/domain/parsing]
[/adapters/postgresql/internal/model] --> [/pkg]
[/adapters/postgresql/internal/other] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/other] --> [/domain/fsmodel]
[/adapters/postgresql/internal/other] --> [/domain/systemmodel]
[/adapters/postgresql/internal/page] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/page] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/page] --> [/domain/core]
[/adapters/postgresql/internal/repository] --> [/pkg]
[/adapters/postgresql/internal/urlmirror] --> [/adapters/postgresql/internal/model]
[/adapters/postgresql/internal/urlmirror] --> [/adapters/postgresql/internal/repository]
[/adapters/postgresql/internal/urlmirror] --> [/domain/parsing]
[/adapters/tmpdata] --> [/domain/agentmodel]
[/adapters/tmpdata] --> [/domain/fsmodel]
[/adapters/tmpdata] --> [/domain/systemmodel]
[/adapters/tmpdata] --> [/pkg]
[/application/configremaper] --> [/config]
[/application/server] --> [/adapters/agent]
[/application/server] --> [/adapters/filestorage]
[/application/server] --> [/adapters/metric]
[/application/server] --> [/adapters/postgresql]
[/application/server] --> [/adapters/tmpdata]
[/application/server] --> [/config]
[/application/server] --> [/controllers/apiagent]
[/application/server] --> [/controllers/apiserver]
[/application/server] --> [/controllers/async]
[/application/server] --> [/controllers/workermanager]
[/application/server] --> [/domain/core]
[/application/server] --> [/domain/systemmodel]
[/application/server] --> [/pkg]
[/application/server] --> [/usecases/agentusecase]
[/application/server] --> [/usecases/attributeusecase]
[/application/server] --> [/usecases/bffusecase]
[/application/server] --> [/usecases/bookusecase]
[/application/server] --> [/usecases/cleanupusecase]
[/application/server] --> [/usecases/deduplicatorusecase]
[/application/server] --> [/usecases/exportusecase]
[/application/server] --> [/usecases/filesystemusecase]
[/application/server] --> [/usecases/hproxyusecase]
[/application/server] --> [/usecases/labelusecase]
[/application/server] --> [/usecases/massloadusecase]
[/application/server] --> [/usecases/parsingusecase]
[/application/server] --> [/usecases/rebuilderusecase]
[/application/server] --> [/usecases/systemusecase]
[/cmd/configremaper] --> [/application/configremaper]
[/cmd/configremaper] --> [/config]
[/cmd/grafanagenerator] --> [/adapters/metric/generator]
[/cmd/grafanagenerator] --> [/config]
[/cmd/server] --> [/application/server]
[/controllers/apiagent] --> [/domain/agentmodel]
[/controllers/apiagent] --> [/domain/core]
[/controllers/apiagent] --> [/openapi/agentapi]
[/controllers/apiagent] --> [/pkg]
[/controllers/apiserver] --> [/controllers/apiserver/agenthandlers]
[/controllers/apiserver] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver] --> [/controllers/apiserver/attributehandlers]
[/controllers/apiserver] --> [/controllers/apiserver/bookhandlers]
[/controllers/apiserver] --> [/controllers/apiserver/deduplicatehandlers]
[/controllers/apiserver] --> [/controllers/apiserver/fshandlers]
[/controllers/apiserver] --> [/controllers/apiserver/hproxyhandlers]
[/controllers/apiserver] --> [/controllers/apiserver/labelhandlers]
[/controllers/apiserver] --> [/controllers/apiserver/massloadhandlers]
[/controllers/apiserver] --> [/controllers/apiserver/systemhandlers]
[/controllers/apiserver] --> [/openapi/serverapi]
[/controllers/apiserver/agenthandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/agenthandlers] --> [/domain/agentmodel]
[/controllers/apiserver/agenthandlers] --> [/domain/core]
[/controllers/apiserver/agenthandlers] --> [/openapi/serverapi]
[/controllers/apiserver/agenthandlers] --> [/pkg]
[/controllers/apiserver/apiservercore] --> [/domain/bff]
[/controllers/apiserver/apiservercore] --> [/domain/core]
[/controllers/apiserver/apiservercore] --> [/domain/fsmodel]
[/controllers/apiserver/apiservercore] --> [/openapi/serverapi]
[/controllers/apiserver/apiservercore] --> [/pkg]
[/controllers/apiserver/attributehandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/attributehandlers] --> [/domain/core]
[/controllers/apiserver/attributehandlers] --> [/openapi/serverapi]
[/controllers/apiserver/attributehandlers] --> [/pkg]
[/controllers/apiserver/bookhandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/bookhandlers] --> [/domain/bff]
[/controllers/apiserver/bookhandlers] --> [/domain/core]
[/controllers/apiserver/bookhandlers] --> [/openapi/serverapi]
[/controllers/apiserver/bookhandlers] --> [/pkg]
[/controllers/apiserver/deduplicatehandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/deduplicatehandlers] --> [/domain/bff]
[/controllers/apiserver/deduplicatehandlers] --> [/domain/core]
[/controllers/apiserver/deduplicatehandlers] --> [/openapi/serverapi]
[/controllers/apiserver/deduplicatehandlers] --> [/pkg]
[/controllers/apiserver/fshandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/fshandlers] --> [/domain/core]
[/controllers/apiserver/fshandlers] --> [/domain/fsmodel]
[/controllers/apiserver/fshandlers] --> [/openapi/serverapi]
[/controllers/apiserver/fshandlers] --> [/pkg]
[/controllers/apiserver/hproxyhandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/hproxyhandlers] --> [/domain/hproxymodel]
[/controllers/apiserver/hproxyhandlers] --> [/openapi/serverapi]
[/controllers/apiserver/hproxyhandlers] --> [/pkg]
[/controllers/apiserver/labelhandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/labelhandlers] --> [/domain/core]
[/controllers/apiserver/labelhandlers] --> [/openapi/serverapi]
[/controllers/apiserver/labelhandlers] --> [/pkg]
[/controllers/apiserver/massloadhandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/massloadhandlers] --> [/domain/core]
[/controllers/apiserver/massloadhandlers] --> [/domain/massloadmodel]
[/controllers/apiserver/massloadhandlers] --> [/openapi/serverapi]
[/controllers/apiserver/massloadhandlers] --> [/pkg]
[/controllers/apiserver/systemhandlers] --> [/controllers/apiserver/apiservercore]
[/controllers/apiserver/systemhandlers] --> [/domain/core]
[/controllers/apiserver/systemhandlers] --> [/domain/parsing]
[/controllers/apiserver/systemhandlers] --> [/domain/systemmodel]
[/controllers/apiserver/systemhandlers] --> [/openapi/serverapi]
[/controllers/apiserver/systemhandlers] --> [/pkg]
[/controllers/internal/worker] --> [/pkg]
[/controllers/workermanager] --> [/controllers/internal/worker]
[/controllers/workermanager] --> [/domain/agentmodel]
[/controllers/workermanager] --> [/domain/core]
[/controllers/workermanager] --> [/domain/fsmodel]
[/controllers/workermanager] --> [/domain/massloadmodel]
[/controllers/workermanager] --> [/domain/parsing]
[/controllers/workermanager] --> [/domain/systemmodel]
[/controllers/workermanager] --> [/pkg]
[/domain/agentmodel] --> [/domain/core]
[/domain/bff] --> [/domain/core]
[/domain/bff] --> [/pkg]
[/domain/core] --> [/pkg]
[/domain/fsmodel] --> [/domain/core]
[/domain/parsing] --> [/domain/core]
[/external] --> [/domain/core]
[/external] --> [/pkg]
[/usecases/agentusecase] --> [/domain/agentmodel]
[/usecases/agentusecase] --> [/domain/core]
[/usecases/agentusecase] --> [/pkg]
[/usecases/attributeusecase] --> [/domain/core]
[/usecases/attributeusecase] --> [/domain/systemmodel]
[/usecases/bffusecase] --> [/domain/bff]
[/usecases/bffusecase] --> [/domain/core]
[/usecases/bffusecase] --> [/domain/fsmodel]
[/usecases/bffusecase] --> [/pkg]
[/usecases/bookusecase] --> [/domain/core]
[/usecases/cleanupusecase] --> [/domain/core]
[/usecases/cleanupusecase] --> [/domain/fsmodel]
[/usecases/cleanupusecase] --> [/domain/systemmodel]
[/usecases/cleanupusecase] --> [/pkg]
[/usecases/deduplicatorusecase] --> [/domain/bff]
[/usecases/deduplicatorusecase] --> [/domain/core]
[/usecases/deduplicatorusecase] --> [/domain/systemmodel]
[/usecases/deduplicatorusecase] --> [/external]
[/usecases/deduplicatorusecase] --> [/pkg]
[/usecases/exportusecase] --> [/domain/agentmodel]
[/usecases/exportusecase] --> [/domain/core]
[/usecases/exportusecase] --> [/domain/parsing]
[/usecases/exportusecase] --> [/external]
[/usecases/exportusecase] --> [/pkg]
[/usecases/filesystemusecase] --> [/domain/core]
[/usecases/filesystemusecase] --> [/domain/fsmodel]
[/usecases/filesystemusecase] --> [/pkg]
[/usecases/hproxyusecase] --> [/domain/agentmodel]
[/usecases/hproxyusecase] --> [/domain/core]
[/usecases/hproxyusecase] --> [/domain/hproxymodel]
[/usecases/hproxyusecase] --> [/domain/massloadmodel]
[/usecases/hproxyusecase] --> [/domain/parsing]
[/usecases/hproxyusecase] --> [/pkg]
[/usecases/labelusecase] --> [/domain/core]
[/usecases/labelusecase] --> [/domain/systemmodel]
[/usecases/massloadusecase] --> [/domain/agentmodel]
[/usecases/massloadusecase] --> [/domain/core]
[/usecases/massloadusecase] --> [/domain/hproxymodel]
[/usecases/massloadusecase] --> [/domain/massloadmodel]
[/usecases/massloadusecase] --> [/domain/parsing]
[/usecases/massloadusecase] --> [/domain/systemmodel]
[/usecases/massloadusecase] --> [/pkg]
[/usecases/parsingusecase] --> [/domain/agentmodel]
[/usecases/parsingusecase] --> [/domain/core]
[/usecases/parsingusecase] --> [/domain/parsing]
[/usecases/parsingusecase] --> [/pkg]
[/usecases/rebuilderusecase] --> [/domain/core]
[/usecases/rebuilderusecase] --> [/pkg]
[/usecases/systemusecase] --> [/domain/systemmodel]
@enduml