// Code generated by ogen, DO NOT EDIT.
package serverAPI

type APIAgentDeletePostRes interface {
	aPIAgentDeletePostRes()
}

type APIAgentListPostRes interface {
	aPIAgentListPostRes()
}

type APIAgentNewPostRes interface {
	aPIAgentNewPostRes()
}

type APIAgentTaskExportPostRes interface {
	aPIAgentTaskExportPostRes()
}

type APIAttributeCountGetRes interface {
	aPIAttributeCountGetRes()
}

type APIBookArchiveIDGetRes interface {
	aPIBookArchiveIDGetRes()
}

type APIBookDeletePostRes interface {
	aPIBookDeletePostRes()
}

type APIBookDetailsPostRes interface {
	aPIBookDetailsPostRes()
}

type APIBookListPostRes interface {
	aPIBookListPostRes()
}

type APIBookRawPostRes interface {
	aPIBookRawPostRes()
}

type APIBookUpdatePostRes interface {
	aPIBookUpdatePostRes()
}

type APIBookVerifyPostRes interface {
	aPIBookVerifyPostRes()
}

type APIDeduplicateBookByPageBodyPostRes interface {
	aPIDeduplicateBookByPageBodyPostRes()
}

type APIDeduplicateBooksByPagePostRes interface {
	aPIDeduplicateBooksByPagePostRes()
}

type APIDeduplicateComparePostRes interface {
	aPIDeduplicateComparePostRes()
}

type APIDeduplicateUniquePagesPostRes interface {
	aPIDeduplicateUniquePagesPostRes()
}

type APIFileIDGetRes interface {
	aPIFileIDGetRes()
}

type APILabelDeletePostRes interface {
	aPILabelDeletePostRes()
}

type APILabelGetPostRes interface {
	aPILabelGetPostRes()
}

type APILabelPresetCreatePostRes interface {
	aPILabelPresetCreatePostRes()
}

type APILabelPresetDeletePostRes interface {
	aPILabelPresetDeletePostRes()
}

type APILabelPresetGetPostRes interface {
	aPILabelPresetGetPostRes()
}

type APILabelPresetListGetRes interface {
	aPILabelPresetListGetRes()
}

type APILabelPresetUpdatePostRes interface {
	aPILabelPresetUpdatePostRes()
}

type APILabelSetPostRes interface {
	aPILabelSetPostRes()
}

type APIPageBodyPostRes interface {
	aPIPageBodyPostRes()
}

type APIParsingBookExistsPostRes interface {
	aPIParsingBookExistsPostRes()
}

type APIParsingPageExistsPostRes interface {
	aPIParsingPageExistsPostRes()
}

type APISystemDeduplicateArchivePostRes interface {
	aPISystemDeduplicateArchivePostRes()
}

type APISystemHandlePostRes interface {
	aPISystemHandlePostRes()
}

type APISystemImportArchivePostRes interface {
	aPISystemImportArchivePostRes()
}

type APISystemInfoGetRes interface {
	aPISystemInfoGetRes()
}

type APISystemWorkerConfigPostRes interface {
	aPISystemWorkerConfigPostRes()
}

type APITaskCreatePostRes interface {
	aPITaskCreatePostRes()
}

type APITaskResultsGetRes interface {
	aPITaskResultsGetRes()
}

type APIUserLoginPostRes interface {
	aPIUserLoginPostRes()
}
