// Code generated by ogen, DO NOT EDIT.

package serverAPI

// OperationName is the ogen operation name
type OperationName = string

const (
	APIAgentDeletePostOperation                  OperationName = "APIAgentDeletePost"
	APIAgentListPostOperation                    OperationName = "APIAgentListPost"
	APIAgentNewPostOperation                     OperationName = "APIAgentNewPost"
	APIAgentTaskExportPostOperation              OperationName = "APIAgentTaskExportPost"
	APIAttributeCountGetOperation                OperationName = "APIAttributeCountGet"
	APIBookArchiveIDGetOperation                 OperationName = "APIBookArchiveIDGet"
	APIBookDeletePostOperation                   OperationName = "APIBookDeletePost"
	APIBookDetailsPostOperation                  OperationName = "APIBookDetailsPost"
	APIBookListPostOperation                     OperationName = "APIBookListPost"
	APIBookRawPostOperation                      OperationName = "APIBookRawPost"
	APIBookVerifyPostOperation                   OperationName = "APIBookVerifyPost"
	APIFileIDGetOperation                        OperationName = "APIFileIDGet"
	APIPageBodyPostOperation                     OperationName = "APIPageBodyPost"
	APIParsingBookExistsPostOperation            OperationName = "APIParsingBookExistsPost"
	APIParsingPageExistsPostOperation            OperationName = "APIParsingPageExistsPost"
	APISystemDeduplicateArchivePostOperation     OperationName = "APISystemDeduplicateArchivePost"
	APISystemHandlePostOperation                 OperationName = "APISystemHandlePost"
	APISystemImportArchivePostOperation          OperationName = "APISystemImportArchivePost"
	APISystemInfoGetOperation                    OperationName = "APISystemInfoGet"
	APISystemRPCDeduplicateFilesPostOperation    OperationName = "APISystemRPCDeduplicateFilesPost"
	APISystemRPCRemoveDetachedFilesPostOperation OperationName = "APISystemRPCRemoveDetachedFilesPost"
	APISystemRPCRemoveMismatchFilesPostOperation OperationName = "APISystemRPCRemoveMismatchFilesPost"
	APISystemWorkerConfigPostOperation           OperationName = "APISystemWorkerConfigPost"
	APIUserLoginPostOperation                    OperationName = "APIUserLoginPost"
)
